---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-teapot
  name: nginx-teapot
  namespace: netology
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nginx-teapot
  template:
    metadata:
      labels:
        app: nginx-teapot
    spec:
      containers:
        - name: nginx-teapot
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
            - containerPort: 443
              name: https
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-teapot
  namespace: netology
spec:
  type: LoadBalancer
  selector:
    app: nginx-teapot
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
