name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v3
    - name: Login to Yandex Cloud Container Registry
      id: login-cr
      uses: yc-actions/yc-cr-login@v1
      with:
        yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
    - name: Build and push to YC
      env:
        CR_REPOSITORY: ${{ secrets.CR_REPOSITORY }}
        CR_REGISTRY: ${{ secrets.CR_REGISTRY }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build . --file Dockerfile --tag cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG --tag cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:latest
        docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG
        docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:latest
        
  deployment:
    runs-on: 'ubuntu-latest'
    needs: build
    steps:
    - name: 'Checkout'
      uses: 'actions/checkout@v1'

    - name: 'Deploy'
      # Parameters are pulled directly from the GitHub deployment event so the
      # configuration for the job here is very minimal.
      uses: 'deliverybot/helm@v1.7.0'
      with:
        helm: helm3
        token: '${{ github.token }}'
        version: '${{ github.sha }}'
        chart: './helm'
        task: 'upgrade'
        namespace: 'netology'
        values: |
          image.repository: "cr.yandex/${{ secrets.CR_REGISTRY }}/${{ secrets.CR_REPOSITORY }}"
        value-files: "./helm/values.yaml"
        
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
